"""Build the team social-feed targets for the arena news scraper.

Reads data/contact_links.json (the contacts source of truth) and writes
data/team_feeds.json with two target lists api/news.mjs consumes:

- youtube: every team channel, resolved to its canonical channel ID
  (fetches /c/, /@handle and /user/ pages to extract channelId) — polled
  via the free RSS feeds.
- instagram: the official @battlebots account plus every PRO-LEAGUE team's
  own account — scraped daily in one Bright Data dataset batch.

Rerun when links are added to contact_links.json.

Usage:
    .venv/bin/python pipeline/build_team_feeds.py
"""

from __future__ import annotations

import json
import pathlib
import re
import sys

import requests

ROOT = pathlib.Path(__file__).resolve().parent.parent
LINKS = ROOT / "data" / "contact_links.json"
TEAMS = ROOT / "data" / "teams.json"
OUT = ROOT / "data" / "team_feeds.json"

UA = {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/126.0 Safari/537.36"}


def channel_id(url: str) -> str | None:
    m = re.search(r"youtube\.com/channel/(UC[\w-]{20,})", url)
    if m:
        return m.group(1)
    try:
        r = requests.get(url, headers=UA, timeout=15,
                         cookies={"SOCS": "CAISAiAD", "CONSENT": "YES+cb"})
        if not r.ok:
            return None
        m = re.search(r'"channelId":"(UC[\w-]{20,})"', r.text) or re.search(
            r'"externalId":"(UC[\w-]{20,})"', r.text
        )
        return m.group(1) if m else None
    except Exception:  # noqa: BLE001
        return None


def main() -> int:
    teams = {t["id"]: t for t in json.loads(TEAMS.read_text())["teams"]}
    links = json.loads(LINKS.read_text())["links"]
    feeds = []
    for bot_id, entry in links.items():
        url = entry.get("team", {}).get("youtube") or entry.get("owner", {}).get("youtube")
        if not url:
            continue
        t = teams[bot_id]
        cid = channel_id(url)
        if not cid:
            print(f"  ! could not resolve {bot_id}: {url}", file=sys.stderr)
            continue
        feeds.append({
            "id": bot_id,
            "bot": t["bot"],
            "team": t.get("team"),
            "active": bool(t.get("active")),
            "channel_id": cid,
        })
        print(f"  {t['bot']:22s} {cid}")
    feeds.sort(key=lambda f: (not f["active"], f["bot"]))

    # the official BattleBots channel: its videos run as official news, never
    # attributed to a team (it was once wrongly linked as Team Monsoon's)
    official_yt = channel_id("https://www.youtube.com/@BattleBots")
    if official_yt:
        feeds.insert(0, {
            "id": None, "bot": None, "team": "BattleBots", "active": True,
            "official": True, "channel_id": official_yt,
        })

    # instagram: the official account + EVERY team's account; facebook: every
    # team's page (official FB posts already come from battlebots.com/news).
    # Both are scraped in one daily Bright Data batch per platform.
    handle = lambda u: u.rstrip("/").rsplit("/", 1)[-1].lower()  # noqa: E731
    instagram = [{
        "id": None, "bot": None, "team": "BattleBots", "official": True,
        "handle": "battlebots", "url": "https://www.instagram.com/battlebots/",
    }]
    facebook = []
    seen_urls = {"instagram": set(), "facebook": set()}
    for bot_id, entry in links.items():
        t = teams[bot_id]
        for platform, out in (("instagram", instagram), ("facebook", facebook)):
            url = entry.get("team", {}).get(platform)
            if not url:
                continue
            # the FB dataset validates urls strictly: canonical www host only,
            # and profile.php ids are rejected outright
            url = url.replace("://m.facebook.com", "://www.facebook.com")
            if platform == "facebook" and "profile.php" in url:
                continue
            if url in seen_urls[platform]:
                continue  # same-team bots share accounts — scrape once
            seen_urls[platform].add(url)
            out.append({
                "id": bot_id, "bot": t["bot"], "team": t.get("team"), "official": False,
                "handle": handle(url), "url": url,
            })

    OUT.write_text(json.dumps({
        "note": "Team feed targets, generated by pipeline/build_team_feeds.py "
                "from data/contact_links.json. Rerun after adding links.",
        "youtube": feeds,
        "instagram": instagram,
        "facebook": facebook,
    }, indent=2, ensure_ascii=False) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(feeds)} youtube channels "
          f"({sum(1 for f in feeds if f['active'])} pro league), "
          f"{len(instagram)} instagram, {len(facebook)} facebook accounts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
